### ISSUE TITLE
"Could not obtain current Hibernate Session" in 3.0.0-RC1 with Grails 3.1.x

### ISSUE THREAD

**Issue by klnprj** [bluesliverx/grails-spring-security-oauth2-provider#114]
1) Using Grails 3.1.4 create new application:
`grails create-app test --profile=web`

2) Add spring-security-oauth2-provider plugin to dependencies in `build.gradle`:
```
compile 'org.grails.plugins:spring-security-oauth2-provider:3.0.0-RC1'
```

3) Generate oauth domain classes:
```
grails s2-init-oauth2-provider com.yourapp Client AuthorizationCode AccessToken RefreshToken
```

4) Launch application and apply for an access token:
```
POST http://localhost:8080/oauth/token?grant_type=password&scope=read&client_id=test&username=test@example.com&password=testtest
```

Result: 
```
{"error":"unauthorized","error_description":"Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread"}
```
 Error in logs:
```
ERROR org.springframework.security.oauth2.provider.client.ClientCredentialsTokenEndpointFilter - An internal error occurred while trying to authenticate the user.
org.springframework.security.authentication.InternalAuthenticationServiceException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:126)
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:143)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:167)
	at org.springframework.security.oauth2.provider.client.ClientCredentialsTokenEndpointFilter.attemptAuthentication(ClientCredentialsTokenEndpointFilter.java:123)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:68)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:73)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:227)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:183)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:140)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:110)
	at org.grails.orm.hibernate.AbstractHibernateGormStaticApi.findWhere(AbstractHibernateGormStaticApi.groovy:335)
	at org.grails.datastore.gorm.GormStaticApi.findWhere(GormStaticApi.groovy:648)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.findWhere(GormEntity.groovy:830)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper$findWhere.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at com.yourapp.Client.findWhere(Client.groovy)
	at com.yourapp.Client$findWhere.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at grails.plugin.springsecurity.oauthprovider.GormClientDetailsService.loadClientByClientId(GormClientDetailsService.groovy:25)
	at org.springframework.security.oauth2.provider.client.ClientDetailsUserDetailsService.loadUserByUsername(ClientDetailsUserDetailsService.java:47)
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.retrieveUser(DaoAuthenticationProvider.java:114)
	... 52 common frames omitted
Caused by: org.hibernate.HibernateException: No Session found for current thread
	at org.grails.orm.hibernate.GrailsSessionContext.currentSession(GrailsSessionContext.java:117)
	at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:1014)
	at org.grails.orm.hibernate.SessionFactoryProxy.getCurrentSession(SessionFactoryProxy.java:148)
	at org.grails.orm.hibernate.GrailsHibernateTemplate.getSession(GrailsHibernateTemplate.java:225)
	... 70 common frames omitted
```

This only fails in Grails 3.1.x - in Grails 3.0.15 everything seems to work.

**Comment by gilinykh** [comment]
Possibly related to https://github.com/grails-plugins/grails-spring-security-core/issues/378

**Comment by bhagwat** [comment]
# Workaround
I found a workaround for the time being. Make these changes if you have not found any workaround yet. I added my own implementation of two classes which does nothing but calling the actual superclass methods but with `@Transactional(readonly=true)` behaviour. 

### src/main/groovy/demo/CustomGormClientDetailsService.groovy
Create CustomGormClientDetailsService groovy class in src 
```
package demo

import grails.transaction.Transactional
import grails.plugin.springsecurity.oauthprovider.GormClientDetailsService
import org.springframework.security.oauth2.provider.*

class CustomGormClientDetailsService extends GormClientDetailsService {
    @Transactional(readOnly = true)
    ClientDetails loadClientByClientId(String clientId) throws ClientRegistrationException {
        super.loadClientByClientId(clientId)
    }
}
```
### src/main/groovy/demo/CustomGormAuthorizationCodeService.groovy
Create CustomGormAuthorizationCodeService groovy class in src 
```
import grails.transaction.Transactional
import grails.plugin.springsecurity.oauthprovider.GormAuthorizationCodeService
import org.springframework.security.oauth2.provider.OAuth2Authentication

class CustomGormAuthorizationCodeService extends GormAuthorizationCodeService {
    @Transactional(readOnly = true) //this will make sure hibernate session is available
    protected void store(String code, OAuth2Authentication authentication) {
        super.store(code, authentication)
    }

    @Transactional(readOnly = true)
    protected OAuth2Authentication remove(String code) {
        super.remove(code)
    }
}

```

### grails-app/conf/spring/resources.groovy
Override the existing beans with your own implementation:

```
import demo*
beans = {
    gormClientDetailsService(CustomGormClientDetailsService) {
        grailsApplication = ref('grailsApplication')
        clientAdditionalInformationSerializer = ref('clientAdditionalInformationSerializer')
    }

    gormAuthorizationCodeService(CustomGormAuthorizationCodeService) {
        grailsApplication = ref('grailsApplication')
        oauth2AuthenticationSerializer = ref('oauth2AuthenticationSerializer')
    }
}
```

Once the fix is available in plugin we can safely remove these classes and corresponding bean definations from resources.groovy.

**Comment by bobby-vandiver** [comment]
Fixed and verified against Grails 3.0.17 and 3.1.7 in 2557e20fb8e808d247dc7dca25d13f3725a79ce0.

**Comment by johngamarra** [comment]
Hi, I'm still having problems with this issue, unfortunately I'm still getting No Hibernate Session, when I try to use the token I get

**Comment by mmzen** [comment]
Exact same issue here:
    - Grails 3.1.9
    - spring-security-core:3.1.1
    - spring-security-oauth2-provider:3.0.0-RC1

`No Session found for current thread. Stacktrace follows:
org.springframework.dao.DataAccessResourceFailureException: Could not obtain current Hibernate Session; nested exception is org.hibernate.HibernateException: No Session found for current thread
	at grails.plugin.springsecurity.oauthprovider.GormClientDetailsService.loadClientByClientId(GormClientDetailsService.groovy:25)
	at grails.plugin.springsecurity.oauthprovider.provider.GrailsOAuth2RequestFactory.extractScopes(GrailsOAuth2RequestFactory.java:102)
	at grails.plugin.springsecurity.oauthprovider.provider.GrailsOAuth2RequestFactory.createAuthorizationRequest(GrailsOAuth2RequestFactory.java:60)
	at grails.plugin.springsecurity.oauthprovider.endpoint.WrappedAuthorizationEndpoint.authorize(WrappedAuthorizationEndpoint.java:20)
	at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:53)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
	at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by bluesliverx** [comment]
This will be fixed once 3.0.0-RC2 is released, see #119.

**Comment by mmzen** [comment]
Issue is unreproducible with 3.0.0-RC2.
Thanks!

**Comment by sagrawal14** [comment]
@bluesliverx thanks for the fix. Do you have any estimated timeline of the release?

**Comment by bobby-vandiver** [comment]
@sagrawal14 Have you tried the 3.0.0-RC2 release?

**Comment by sagrawal14** [comment]
@bobby-vandiver I don't see the 3.0.0-RC2 release on the [bintray](https://bintray.com/bluesliverx/grails-plugins/spring-security-oauth2-provider)

**Comment by sagrawal14** [comment]
@bobby-vandiver got the release as described in #119. Sorry for the noise.
