### ISSUE TITLE
Getting the same access token on every 2 subsequent requests 

### ISSUE THREAD

**Issue by ferasodh** [bluesliverx/grails-spring-security-oauth2-provider#82]
Hi,

I'm facing this issue when requesting an access token for the same user I go the same access token on every 2 subsequent requests. This happens even when the access token is not expired. Note that the second time I can't use this access token to authenticate. 
Is this a true behavior or there is a bug in the plugin or in my configuration? I'm using grails 2.4.2 and RC2 version of the plugin.

Thanks,

**Comment by bluesliverx** [comment]
Try the RC3 version of the plugin.  There was a relevant bug that was fixed around access tokens.  @bobby-vandiver, correct me if I'm wrong on this.

**Comment by ferasodh** [comment]
Thanks Brian. Actually as you said this related to RC2 bug. RC3 fixes this but still if I requested a new access token I still get the same one again.Shouldn't I expect a new access token when sending a new request?

**Comment by dynamind** [comment]
This is default behaviour. Check the `createAccessToken` method in `DefaultTokenServices`:

    public OAuth2AccessToken createAccessToken(OAuth2Authentication authentication) throws AuthenticationException {
        OAuth2AccessToken existingAccessToken = this.tokenStore.getAccessToken(authentication);
        OAuth2RefreshToken refreshToken = null;
        if(existingAccessToken != null) {
            if(!existingAccessToken.isExpired()) {
                this.tokenStore.storeAccessToken(existingAccessToken, authentication);
                return existingAccessToken;
            }
    ...

This shows that existing access tokens are returned when they haven't expired.

**Comment by bluesliverx** [comment]
If you wanted to override this, you could subclass `DefaultTokenServices` and override it in `resources.groovy`.
